In [1]:
import numpy as np
import matplotlib as plt

<img src="https://static.leiphone.com/uploads/new/article/740_740/201701/5881deecab918.png?imageMogr2/format/jpg/quality/90">

In [3]:
import torch

## Torch.tensor

Торч почти numpy, только вместо array теперь tensor. Каждый torch.tensor является частью вычислительного графа. 

In [ ]:
torch.tensor()

In [ ]:
torch.rand()

In [ ]:
torch.ones()

In [ ]:
torch.diag()

Вместо .shape в torch .size

Вместо .reshape в торч .view

Связка с numpy работает с помощью .numpy()

In [12]:
t = torch.ones((1,2))

In [13]:
t

tensor([[1., 1.]])

In [14]:
t_np = t.numpy()

In [15]:
t_np

array([[1., 1.]], dtype=float32)

In [17]:
t += 1

In [19]:
t

tensor([[2., 2.]])

In [20]:
t_np

array([[2., 2.]], dtype=float32)

Обратно torch.from_numpy

In [21]:
n = np.ones((1,2))

In [22]:
n

array([[1., 1.]])

In [23]:
n_torch = torch.from_numpy(n)

In [24]:
n_torch

tensor([[1., 1.]], dtype=torch.float64)

In [25]:
n += 1

In [26]:
n

array([[2., 2.]])

In [27]:
n_torch

tensor([[2., 2.]], dtype=torch.float64)

## torch.backwards

Мы можем регулировать хотим ли мы чтобы прокидывались градиенты через тензор с помощью torch.tensor(..., requires_grad = True/False). Это важно потому что нам не надо прокидывать градиенты по входу нейронной сети например. 

In [30]:
x = torch.tensor(1., requires_grad=True)
y = torch.tensor(3., requires_grad=True)
z = torch.tensor(5., requires_grad=True)

In [31]:
w = (x + y) * z 

In [32]:
w

tensor(20., grad_fn=<ThMulBackward>)

In [33]:
w.backward()

In [37]:
z.grad

tensor(4.)

In [38]:
y.grad

tensor(5.)

In [39]:
x.grad

tensor(5.)

In [40]:
torch.__version__

'0.4.1'